version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: hola
      DB_NAME: prueba

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: hola
    ports:
      - "3306:3306"